name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: tiawl/spaceporn-action-env@v1.0.3
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: ${{ env.zig_version }}
    - name: Test building examples
      shell: bash
      run: |
        zig build --build-file "${GITHUB_WORKSPACE}/examples/build.zig"
        env -C ./examples ./zig-out/bin/examples
  windows:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - i386
        include:
          - arch: amd64
            msystem: UCRT64
          - arch: i386
            msystem: MINGW32
    runs-on: windows-2022
    env:
      LDFLAGS: -s
      SUFFIX: windows-${{ matrix.arch }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: tiawl/spaceporn-action-env@v1.0.3
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: ${{ env.zig_version }}
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{ matrix.msystem }}
        install: >-
          base-devel
          git
          autoconf
          automake
          libtool
        pacboy: >-
          toolchain:p
    - name: Test building and running examples
      shell: bash
      run: |
        zig build --build-file "${GITHUB_WORKSPACE}/examples/build.zig"
        env -C "${GITHUB_WORKSPACE}/examples" ./zig-out/bin/examples
