name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  examples:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: tiawl/spaceporn-action-env@v1.0.3
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: ${{ env.zig_version }}
    - name: Test building examples
      shell: bash
      run:
        zig build --build-file "${GITHUB_WORKSPACE}/examples/build.zig"
    - name: Run examples
      shell: bash
      run:
        ./examples/zig-out/bin/examples
