name: ci

on:
  pull_request:
    branches:
      - trunk

jobs:
  examples:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
    - uses: tiawl/spaceporn-action-env@v1.0.3
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v1
      with:
        version: ${{ env.zig_version }}
    - if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: ${{ matrix.msystem }}
        install: >-
          base-devel
          git
          autoconf
          automake
          libtool
        pacboy: >-
          toolchain:p
    - if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        git clone https://github.com/jqlang/jq test
        env -C ./test git submodule update --init
        env -C ./test autoreconf -i
        env -C ./test ./configure --disable-docs --disable-valgrind --with-oniguruma=builtin --disable-shared --enable-static --enable-all-static CFLAGS="-O2 -pthread -fstack-protector-all"
        cat test/Makefile
        exit 1
    - name: Test building examples
      shell: bash
      run:
        zig build --build-file "${GITHUB_WORKSPACE}/examples/build.zig"
    - name: Run examples
      shell: bash
      run:
        env -C ./examples ./zig-out/bin/examples
